apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: {{ .Release.Namespace }}
data:
    key1: "bumlux"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap-v2
  namespace: {{ .Release.Namespace }}
data:
  key1: "{{ .Values.key2 | quote }}"
